baseURL = 'https://zh1995.netlify.com/'
title = 'This is title'
theme = 'hugo-book'
defaultContentLanguage = 'zh'
disqusShortname = 'rwzsjfm'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookComments = true
  BookSearch = true
