baseURL = 'https://zh1995.netlify.com/'
title = '贺老师的回忆录'
theme = 'hugo-book'
defaultContentLanguage = 'zh'
disqusShortname = 'rwzsjfm'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookComments = true
  BookSearch = true
